### ISSUE TITLE
Impossible to install jsctags

### ISSUE THREAD

**Issue by shenron** [ramitos/jsctags#59]
Hello,

Something is broken I can't install jsctags:
>191 silly fetchPackageMetaData error for acorn-jsx@github:ramitos/acorn-jsx#6683232 Command failed: /usr/bin/git checkout 6683232
191 silly fetchPackageMetaData error: pathspec '6683232' did not match any file(s) known to git.

...

>193 verbose stack Error: Command failed: /usr/bin/git checkout 6683232
193 verbose stack error: pathspec '6683232' did not match any file(s) known to git.

Thank you very much

**Comment by shenron** [comment]
I think I understood the problem,

The dependency [`ramitos/tern-jsx`](https://github.com/ramitos/tern-jsx/commits/fc9b687ee6b9258dab63e59d4580338b6138873d/package.json) has been update without change the version (since some years).
To force to have the last version, the package.json use a specific commit, I don't really know why but this commit is broken.

I just replaced:

`"tern-jsx": "github:ramitos/tern-jsx#fc9b687"` by
`"tern-jsx": "ramitos/tern-jsx#fc9b687"`

The fork with the fix:
https://github.com/shenron/jsctags

**Comment by sergioramos** [comment]
fixed in https://github.com/ramitos/jsctags/commit/fdfd930092dfb2aa52f048ac2d6e94eeb9ad6aed

**Comment by itsonlycode** [comment]
The fix that was used to call this closed has never been merged and didn't pass checks ... issue still remains
